### ISSUE TITLE
Doesn't work with umlauts

### ISSUE THREAD

**Issue by bfncs** [pronique/CakePHP-Sluggable-Behavior#1]
I just tried out the behaviour and it definitely doesn't work with german Umlauts. I initialized it like this:

```
var $actsAs = array(
  'Sluggable.Sluggable' => array(
    'translations' => 'utf-8',
  ),
); 
```

And a title of `Prüfung` turns out as slug `pr-fung`.

**Comment by TeckniX** [comment]
BoundaryFunctions - I'm pretty sure umlauts are not allowed in a url either. 
Translations of utf-8 isn't done via magic. If you look at the SluggableBehavior.php you'll notice under the translation array that there is a simple 1-1 association between the ascii code of a character and it's translation.
https://github.com/pronique/CakePHP-Sluggable-Behavior/blob/master/Model/Behavior/SluggableBehavior.php#L246

Simply figure out what your  `ü` translates to and update the code to have 1 additional conversion for that character.

edit: 
this line should've translated your char: `chr(195).chr(188) => 'u'` to u.
I would check to see what your char translates to in ascii.

**Comment by TeckniX** [comment]
Furthermore, I did a quick test using the string translation and the word provided:
https://gist.github.com/4513292

The function sends out the proper slug of: `prufung`, when provided with a label/title/string of `Prüfung`

I would check that your server doesn't convert the data you're passing before the function gets to it. You could have another clean-up function that converts the umlaut as a 'space', which would then become that dash.

**Comment by bfncs** [comment]
Thanks for your effort in testing this!
Since this is already a long time ago, I'll first have to set up anything again to test this again. What is definitely something already worth to point out, is, that it would be great if you could do your umlaut conversions like this:

```
"Ä"  => "Ae"
"ä" => "ae"
"Ö" => "Oe"
"ö" => "oe"
"Ü" => "Ue"
"ü" => "ue"
"ß" => "ss"
```

**Comment by TeckniX** [comment]
Entschuldigung, ich habe nicht die Datum überprüfen. :)
In any case, you can modify the translation, so that the text is converted as the above - I'm not sure what is more grammatically correct, your translation, or the existing one - 
What would make more sense for ein 'Deutschländer'?

**Comment by bfncs** [comment]
Thanks a lot for caring so much!

I still wasn't able to put that case together again, I'll have to start something new, might take a while.
In German it's always better to translate the umlaut to it's two letter version, as pointed out above.

See for example what the Wikipedia knows about [Ü](http://en.wikipedia.org/wiki/%C3%9C#U-umlaut):

> In other languages that do not have the letter as part of the regular alphabet or in limited character sets such as ASCII, U-umlaut is frequently replaced with the two-letter combination "ue".

But I didn't give a thought about any other languages, and it seems in other languges there are differences between the spelling forms. So maybe it would be great to make both behaviours available and make the user choose?

**Comment by TeckniX** [comment]
the patch would be pretty easy to make - feel free to add it in ;)
